version: '3.0'

services:
  grafana:
    container_name: 'cubismgrafana-panel'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
    ports:
      - 4000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/cubismgrafana-panel
      - ./provisioning:/etc/grafana/provisioning
